definitions:
  APIResponse:
    required: 
      - class_names
      - result
    properties:
      class_names:
        items:
          type: string
        type: array
      result:
        items:
          type: string
        type: array
    type: object
  APIRequest:
    type: object
    properties:
      fooStartDate:
        type: string
      bar_StartDate:
        type: string
    required:
      - fooStartDate
      - bar_StartDate
info:
  title: Example
  version: 0.0.0
paths:
  /foo:
    post:
      consumes:
        - application/json
      description: ''
      operationId: extract_description
      parameters:
        - in: body
          name: some_html
          required: true
          schema:
            $ref: '#/definitions/APIRequest'
      produces:
        - application/json
      responses:
        '200':
          description: result
          schema:
            $ref: '#/definitions/APIResponse'
      summary: 'Submit HTML, recieve extractions'
schemes:
  - http
swagger: '2.0'
